apiVersion: v1
kind: Namespace
metadata:
  name: demo
--- 

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: demo
spec:
  hard:
    pods: "6"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi
#    requests.nvidia.com/gpu: 4

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: demo
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "0"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"