apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotas
  namespace: demo
  labels:
    app: quotas
spec:
  replicas: 4
  selector: 
    matchLabels:
      app: quotas
  template:
    metadata:
      labels:
        app: quotas
    spec:
      containers:
      - name: quotas
        image: nginxdemos/hello:0.2
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "500m"