apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  namespace: demo
  labels:
    app: hello
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: nginxdemos/hello:0.1 #tags 0.1 , 0.2 and plain-text available 
        ports:
        - name: http
          containerPort: 80