apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  namespace: demo
  labels:
    app: hello
spec:
  selector: 
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080