apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes
  namespace: demo
  labels:
    app: probes
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: probes
  template:
    metadata:
      labels:
        app: probes
    spec:
      containers:
      - name: liveness
        image: k8s.gcr.io/busybox
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5 #Default 0 
          periodSeconds: 5 #Default 10 seconds. Minimum value is 1.
          timeoutSeconds: 1 #Defaults 1 second. Minimum value is 1.
          successThreshold: 1 #Defaults 1. Minimum value is 1.
          failureThreshold: 3 #Defaults 3. Minimum value is 1.
