apiVersion: v1
kind: Service
metadata:
  name: helloweb
  namespace: demo
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: 8080 # or name
  type: ClusterIP #None | ClusterIP | NodePort | Loadbalancer | ExternalName