apiVersion: v1
kind: Service
metadata:
  name: helloweb
  namespace: demo
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: 80 # or name
  type: NodePort #None | ClusterIP | NodePort | Loadbalancer | ExternalName
