---

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  privileged: false
  allowPrivilegeEscalation: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'secret'
    - 'downwardAPI'
    - 'projected'
    - 'persistentVolumeClaim'
  AllowedCapabilities:
  - 'NET_RAW'           # add possibiltiy to ping
  - 'NET_BIND_SERVICE'  # add possibility to open ports below 1024
  DefaultAddCapabilities: # automaticaly add capabilities to pods
  - 'NET_BIND_SERVICE'
  hostNetwork: false
  hostIPC: false
  hostPID: false
