apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-killer-sa
  namespace: demo

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-killer-clusterrole
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-killer-binding
subjects:
- kind: ServiceAccount
  name: pod-killer
  namespace: demo
roleRef:
  kind: ClusterRole
  name: pod-killer-clusterrole
  apiGroup: rbac.authorization.k8s.io
